[pytest]
python_files = test_*.py
testpaths =
	day_1_messy_list
	day_2_inventory_audit
	day_6_trip_calculator
	day_8_frequency_calculator
	day_10_nested_gradebook
	day_12_modular_validator
	day_13_best_seller
	day_15_library_system
	day_16_the_data_sanitiser
	day_17_csv_parser
	day_19_nested_dictionary